name: "Bug Report"
description: "Found a bug in Elgg? Please report it so we can fix it."
title: "[Bug]: "
labels: "bug"
body:
  - type: input
    attributes: 
      label: "Elgg Version"
      description: "Which version of Elgg is affected"
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: "Source of your Elgg installation"
      description: "How did you install Elgg"
      options:
        - label: "Elgg.org website"
        - label: "Composer install"
        - label: "GIT clone"
        - label: "Other"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Steps to reproduce"
      description: "Steps to reproduce the bug"
      value: |
        1.
        2.
        3.
        ...
  - type: textarea
    attributes:
      label: "Expected behaviour"
      description: "A clear and concise description of what you expected to happen"
  - type: textarea
    attributes:
      label: "Additional notes"
      description: "Is there something more you think we should know"
