name: CodeClimate

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Test & publish code coverage
    - uses: shivammathur/setup-php@v1
      with:
        php-version: '7.4'
        coverage: xdebug
    - uses: paambaati/codeclimate-action@v2.2.4
      env:
        CC_TEST_REPORTER_ID: d76acdcc6ab2bf6d8f4a5af52ed410687510a0c3731d451a6884f75ee8b98117
      with:
        coverageCommand: vendor/bin/phpunit --coverage-text --coverage-clover
