name: CodeClimate

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Test & publish code coverage
      uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'
          coverage: xdebug
