name: CodeClimate

on: [push, pull_request]

jobs:
  code-coverage:
    name: Code Coverage

    runs-on: ubuntu-latest

    steps:
      - name: Prepare PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'
          coverage: xdebug
          
      - name: Generate Coverage Report
        
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12'
        
      - uses: paambaati/codeclimate-action@v2.2.4
        env:
          CC_TEST_REPORTER_ID: d76acdcc6ab2bf6d8f4a5af52ed410687510a0c3731d451a6884f75ee8b98117
        with:
          coverageCommand: vendor/bin/phpunit --coverage-text --coverage-clover
