name: Lint checks
on: [pull_request, push]
jobs:
  commit_message:
    name: Validate the commit message
    runs-on: ubuntu-16.04
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Check format
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^((Merge )|(Revert )|((\w*)\(([\w]+)\)\: ([^\n]*)(\n\n?(.*))?)$)'
          flags: 'is'
          error: 'Invalid commit message format'
          excludeTitle: true
          excludeDescription: true
          checkAllCommitMessages: true
          accessToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Check line length
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^.{1,160}(\n|$)'
          flags: ''
          error: 'Maximun line length of 160 characters exceeded on the first line'
          excludeTitle: true
          excludeDescription: true
          checkAllCommitMessages: true
          accessToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Check type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^((Merge )|(Revert )|(feat(ure)?|fix(es|ed)?|doc(s)?|chore|perf(ormance)?|security|deprecate(s)?)?\()'
          flags: 'is'
          error: 'Invalid commit message type'
          excludeTitle: true
          excludeDescription: true
          checkAllCommitMessages: true
          accessToken: ${{ secrets.GITHUB_TOKEN }}
